plugins {
    id 'com.android.application'
}

android {
    namespace 'com.firewolf.xiaolinstudy'
    compileSdk 35

    defaultConfig {
        applicationId 'com.firewolf.xiaolinstudy'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '1.3.0'
        buildConfigField 'String', 'APP_CENTER_URL', '"https://apps.lxvb.top"'

        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
