plugins {
    id 'com.android.application'
}

android {
    namespace 'com.firewolf.lingosprout'
    compileSdk 35

    defaultConfig {
        applicationId 'com.firewolf.lingosprout'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.0.1'

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        buildConfig = false
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:core:1.7.0'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
}
