plugins {
    id 'com.android.application'
}

android {
    namespace 'com.firewolf.lingosprout'
    compileSdk 35

    defaultConfig {
        applicationId 'com.firewolf.lingosprout'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'

        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        buildConfig = false
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
